### ISSUE TITLE
Incompatible with anki-2.1.21beta1

### ISSUE THREAD

**Issue by Cupbox** [ijgnd/anki__show_due_siblings_in_order__no_same_day_spacing_randomization_for_siblings#1]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'show new siblings in order  no same day spacingrandomization for new siblings':
Traceback (most recent call last):
  File "aqt\addons.py", line 205, in loadAddons
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\268644742\__init__.py", line 1, in <module>
    from . import no_sameday_spacing_for_siblings
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\268644742\no_sameday_spacing_for_siblings.py", line 10, in <module>
    from anki.lang import getLang
ImportError: cannot import name 'getLang' from 'anki.lang' (C:\Program Files\Anki\anki\lang.pyc)

**Comment by ijgnd** [comment]
thanks for the report. I just uploaded a new version to ankiweb. Could you update and try again and let me know if this works for you and if you notice other problems.

**Comment by Cupbox** [comment]
Works perfectly. Thank you very much.
